Made NoteRepository singleton
vladyslav-babych/Notes pull request #3
Opened 2022-08-01 16:01 UTC by vladyslav-babych

1. Removed redundant imports
2. Edited `NoteDatabase` class
3. Made `NoteRepository` singleton

2022-08-01 18:32 UTC, RuslanKharkevych requested changes

2022-08-01 18:32 UTC, RuslanKharkevych commented on app/src/main/java/com/otaman/notes/viewmodel/EditNoteViewModel.kt
> +        repository!!.updateNote(note)
`repository` should not be nullable

2022-08-01 18:32 UTC, RuslanKharkevych commented on app/src/main/java/com/otaman/notes/model/room/NoteDatabase.kt
> +                INSTANCE ?: buildDatabase(context).also { INSTANCE = it }
`INSTANCE` is always null on line 18. Actually, I don't see any issues with `NoteDatabase` class before changes

2022-08-02 06:40 UTC, RuslanKharkevych commented on app/src/main/java/com/otaman/notes/viewmodel/EditNoteViewModel.kt
> +        repository!!.updateNote(note)
You removed the force-wrapping operator, but repository is still nullable

2022-08-02 06:53 UTC, vladyslav-babych commented on app/src/main/java/com/otaman/notes/viewmodel/EditNoteViewModel.kt
> +        repository!!.updateNote(note)
Probably fixed

2022-08-02 07:28 UTC, RuslanKharkevych approved these changes

2022-08-02 07:53 UTC, merged